[package]
name = "abei-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "阿贝后端服务：账单邮箱、反馈存储与 GitHub issue 同步。"

[dependencies]
abei-core.workspace = true
async-http-proxy.workspace = true
async-imap.workspace = true
axum.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
deadpool-postgres.workspace = true
futures-util.workspace = true
mail-parser.workspace = true
oauth2.workspace = true
reqwest.workspace = true
rustls-native-certs.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
